baseurl = "https://afif.js.org/"
title = "blogzam"
theme = "zam"

# disqus & googleAnalytics
DisqusShortname = ""
googleAnalytics = "" 


# Biodata Author
[author]
#site author
    name = "ilzam afif"
    homepage = "https://twitter.com/ilzam27_"
    bio = ""
# Untuk deskripsi tag meta di homepag
description = "Jangan Lupa Bahagia"


[frontmatter]
date = ["date", "publishDate", "lastmod"]
lastmod = [":git", "lastmod", "date", "publishDate"]
publishDate = ["publishDate", "date"]
expiryDate = ["expiryDate"]


[menu]
  [[menu.main]]
    identifier = "github"
    name = "Github"
    url = "https://github.com/ilzamafif"
    wight = 1